from __future__ import annotations

import json
import os
from functools import lru_cache
from pathlib import Path
from typing import Any

from agentmemory.providers.localjson import LocalJsonProvider
from agentmemory.providers.mem0 import Mem0Provider
from agentmemory.providers.base import (
    BaseMemoryProvider,
    MemoryRecord,
    ProviderCapabilities,
    ProviderConfigurationError,
    ProviderRuntimePolicy,
)


def _looks_like_agentmemory_root(path: Path) -> bool:
    markers = [
        path / "pyproject.toml",
        path / "scripts" / "run-agentmemory-python.sh",
        path / "scripts" / "run-agentmemory-python.ps1",
        path / "web",
    ]
    return any(marker.exists() for marker in markers)


def discover_base_dir() -> Path:
    explicit = os.environ.get("AGENTMEMORY_HOME")
    if explicit:
        return Path(explicit).expanduser().resolve()

    cwd = Path.cwd().resolve()
    if _looks_like_agentmemory_root(cwd):
        return cwd

    for candidate in Path(__file__).resolve().parents:
        if _looks_like_agentmemory_root(candidate):
            return candidate

    return cwd


BASE_DIR = discover_base_dir()
CONFIG_PATH = BASE_DIR / "agentmemory.config.json"
ENV_PATH = BASE_DIR / ".env"
RUNTIME_DIR = BASE_DIR / "data"
PLACEHOLDER_KEYS = {"paste-your-openrouter-key-here", "YOUR_OPENROUTER_API_KEY"}


def load_dotenv(env_path: Path = ENV_PATH, *, override: bool = False) -> dict[str, str]:
    loaded: dict[str, str] = {}
    if not env_path.exists():
        return loaded

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if override or key not in os.environ:
            os.environ[key] = value
        loaded[key] = value
    return loaded


load_dotenv()

def default_runtime_config() -> dict[str, Any]:
    registry = provider_registry()
    default_provider_name = "mem0"
    default_provider = registry[default_provider_name]
    return {
        "runtime": {
            "provider": default_provider_name,
            "runtime_dir": str(RUNTIME_DIR),
            "api_host": "127.0.0.1",
            "api_port": 8765,
        },
        "providers": {
            default_provider_name: default_provider.default_provider_config(runtime_dir=str(RUNTIME_DIR)),
        },
    }


def write_runtime_config(config: dict[str, Any]) -> None:
    CONFIG_PATH.write_text(json.dumps(config, ensure_ascii=True, indent=2) + "\n", encoding="ascii")
    clear_caches()


@lru_cache(maxsize=1)
def load_runtime_config_with_source() -> tuple[dict[str, Any], str, Path]:
    if CONFIG_PATH.exists():
        return json.loads(CONFIG_PATH.read_text(encoding="ascii")), "generic", CONFIG_PATH
    return default_runtime_config(), "default", CONFIG_PATH


def load_runtime_config() -> dict[str, Any]:
    return load_runtime_config_with_source()[0]


def current_api_host() -> str:
    config = load_runtime_config()
    return os.environ.get("AGENTMEMORY_API_HOST", config["runtime"].get("api_host", "127.0.0.1"))


def current_api_port() -> int:
    config = load_runtime_config()
    return int(os.environ.get("AGENTMEMORY_API_PORT", str(config["runtime"].get("api_port", 8765))))


def provider_registry() -> dict[str, type[BaseMemoryProvider]]:
    return {
        "localjson": LocalJsonProvider,
        "mem0": Mem0Provider,
    }


def provider_class(provider_name: str) -> type[BaseMemoryProvider]:
    registry = provider_registry()
    if provider_name not in registry:
        raise ProviderConfigurationError(f"Unknown memory provider: {provider_name}")
    return registry[provider_name]


@lru_cache(maxsize=1)
def get_provider() -> BaseMemoryProvider:
    config, _source, _path = load_runtime_config_with_source()
    provider_name = config["runtime"]["provider"]
    provider_type = provider_class(provider_name)
    provider = provider_type(runtime_config=config["runtime"], provider_config=config["providers"][provider_name])
    return provider


def clear_caches() -> None:
    load_runtime_config_with_source.cache_clear()
    get_provider.cache_clear()


def ensure_default_runtime_config() -> dict[str, Any]:
    if not CONFIG_PATH.exists():
        write_runtime_config(default_runtime_config())
    return load_runtime_config()


def write_env_values(values: dict[str, str]) -> None:
    current: dict[str, str] = {}
    if ENV_PATH.exists():
        current.update(load_dotenv(ENV_PATH, override=False))
    current.update({k: v for k, v in values.items() if v is not None})

    lines = [
        "# AgentMemory local environment",
        "# Generated by agentmemory",
    ]
    for key in sorted(current):
        lines.append(f"{key}={current[key]}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    load_dotenv(override=True)
    clear_caches()


def active_provider_name() -> str:
    config = load_runtime_config()
    return config["runtime"]["provider"]


def active_provider_capabilities() -> ProviderCapabilities:
    return get_provider().capabilities()


def active_provider_runtime_policy() -> ProviderRuntimePolicy:
    return get_provider().runtime_policy()


def runtime_info() -> dict[str, Any]:
    config, source, config_path = load_runtime_config_with_source()
    provider = get_provider()
    runtime = config["runtime"]
    return {
        "base_dir": str(BASE_DIR),
        "config_path": str(config_path),
        "env_path": str(ENV_PATH),
        "runtime_dir": runtime.get("runtime_dir", str(RUNTIME_DIR)),
        "api_host": current_api_host(),
        "api_port": current_api_port(),
        "provider": active_provider_name(),
        "capabilities": active_provider_capabilities(),
        "runtime_policy": active_provider_runtime_policy(),
        "config_source": source,
        **provider.runtime_info(),
    }


def health() -> dict[str, Any]:
    return {"ok": True, **runtime_info()}


def memory_add(*, messages, user_id=None, agent_id=None, run_id=None, metadata=None, infer=True, memory_type=None):
    return get_provider().add_memory(
        messages=messages,
        user_id=user_id,
        agent_id=agent_id,
        run_id=run_id,
        metadata=metadata,
        infer=infer,
        memory_type=memory_type,
    )


def memory_search(*, query, user_id=None, agent_id=None, run_id=None, limit=10, filters=None, threshold=None, rerank=True):
    return get_provider().search_memory(
        query=query,
        user_id=user_id,
        agent_id=agent_id,
        run_id=run_id,
        limit=limit,
        filters=filters,
        threshold=threshold,
        rerank=rerank,
    )


def memory_list(*, user_id=None, agent_id=None, run_id=None, limit=100, filters=None):
    return get_provider().list_memories(
        user_id=user_id,
        agent_id=agent_id,
        run_id=run_id,
        limit=limit,
        filters=filters,
    )


def memory_get(memory_id) -> MemoryRecord:
    return get_provider().get_memory(memory_id)


def memory_update(*, memory_id, data, metadata=None):
    return get_provider().update_memory(memory_id=memory_id, data=data, metadata=metadata)


def memory_delete(*, memory_id):
    return get_provider().delete_memory(memory_id=memory_id)


def memory_list_scopes(*, limit: int = 200, kind: str | None = None, query: str | None = None):
    return get_provider().list_scopes(limit=limit, kind=kind, query=query)
